export const V7_GSAP_SECTION_CUE_PLANS = Object.freeze({
  openingHeadline: Object.freeze({
    sequenceStart: 0,
    openingFieldIn: 0,
    openingPlanesIn: 0,
    headlineIn: 0.32,
    openingCtaIn: 0.68,
    mascotRise: 2.5,
    mascotArc: 3.5,
    mascotSettle: 4.75,
    medallionsIn: 5,
    reelTravel: 5,
    medallionTravel: 5,
    openingCtaOut: 8.75,
    headlineArchitecture: 9.25,
    medallionsDim: 9.25,
    headlineFlood: 10.2,
    planesOut: 10.28,
    openingFieldOut: 10.68,
    headlineOut: 11.05,
    planesClear: 11.12,
    headlineCleared: 11.75,
  }),
  basicSequence: Object.freeze({
    phoneEntry: 11.9,
    basicTierOut: 14.25,
    standardTierIn: 14.37,
  }),
  standardSequence: Object.freeze({
    standardTierOut: 14.91,
    proTierIn: 15.03,
    secondStandardPrepare: 25.33,
    secondPhonePrepare: 25.34,
    secondCardsPrepare: 25.34,
    secondPhoneIn: 25.34,
    secondMascotSettle: 25.34,
    secondCardsIn: 25.38,
  }),
  phoneMaterial: Object.freeze({
    mascotLongHold: 14.45,
    materialStart: 15.6,
    materialMiddle: 15.9,
    materialHigh: 16.25,
    materialSecondClip: 16.1,
    materialPeak: 16.6,
    materialFinalClip: 16.65,
    outlineStart: 16.65,
    phoneBodyClear: 16.85,
    blockSceneIn: 16.95,
    ghostCellsIn: 17,
    mascotMaterialHold: 17.1,
    phoneExit: 17.15,
    readableHeadline: 17.8,
    phoneBodyRestore: 18.25,
    phoneMaterialReset: 18.25,
    phoneUiReset: 19.5,
    phoneReturnPrepare: 18.25,
    phoneReturn: 19.6,
    outlineReturn: 19.63,
    ghostCellsOut: 19.05,
    blockSceneOut: 19.63,
    outlineOut: 20,
    sideCardsIn: 19.85,
    mascotAttach: 20.3,
    fourthCardIn: 20.57,
    cueOut: 21.1,
    firstSequenceEnd: 21.6,
    firstClusterEnd: 23,
  }),
  proEntryAtmosphere: Object.freeze({
    violetRise: 23,
    mascotVioletSettle: 23.72,
    violetMedallionsIn: 23.55,
    secondHeadlineIn: 24.25,
    violetMedallionDrift: 24.25,
    secondCtaIn: 24.55,
    blueRise: 25.55,
    violetContentOut: 25.55,
    coralRise: 27.75,
    proAtmosphereIn: 27.75,
    proTierIn: 28.05,
    proMascotSettle: 28.05,
    coralHeadlineIn: 28.05,
    coralHeadlineOut: 29.15,
    focalConvergenceIn: 29.22,
    lessonObjectIn: 29.3,
    focalConvergenceOut: 29.58,
    lessonGlintIn: 29.66,
    lessonObjectAccent: 29.91,
    lessonGlintOut: 30.18,
    lessonObjectRestore: 30.2,
    lessonObjectOut: 30.5,
  }),
  proProofApplication: Object.freeze({
    proofPhonePrepare: 30.45,
    proofPhoneIn: 30.45,
    proofWallIn: 30.5,
    proofMascotIn: 30.5,
    proofCardsIn: 30.55,
    proofWallDrift: 31.05,
    proofWallOut: 32.25,
  }),
  footerClosing: Object.freeze({
    darkCampaignIn: 32.25,
    atmosphereOut: 32.25,
    proofPhoneOut: 32.25,
    closingMascotPrepare: 32.25,
    closingPhonePrepare: 32.62,
    closingPhoneIn: 32.62,
    finalCampaignIn: 32.62,
    closingMascotIn: 32.66,
    finalCtaIn: 32.9,
  }),
  mascotSafariLifecycle: Object.freeze({
    handoffStart: 29.32,
    handoffSeam: 29.45,
    handoffEnd: 29.91,
  }),
} as const);

export type V7GsapSectionName = keyof typeof V7_GSAP_SECTION_CUE_PLANS;
export type V7GsapCueName<Section extends V7GsapSectionName> = (
  keyof (typeof V7_GSAP_SECTION_CUE_PLANS)[Section]
);

export function v7GsapCueAt<Section extends V7GsapSectionName>(
  section: Section,
  cue: V7GsapCueName<Section>,
): number {
  return V7_GSAP_SECTION_CUE_PLANS[section][cue] as number;
}

export function selectV7GsapCueAt<Section extends V7GsapSectionName>(
  section: Section,
  cue: V7GsapCueName<Section>,
  legacyReferenceTime: number,
  contractEnabled: boolean,
) {
  return contractEnabled ? v7GsapCueAt(section, cue) : legacyReferenceTime;
}
